### PR TITLE
Update repo to OPAM 2.0 and add extra packages

### LINKED ISSUE #15: updated repo
FYI, I have upgraded this repo to OPAM 2.0 format, added new versions of cross toolchains, and ported extra packages in [dboris/opam-cross-ios](https://github.com/dboris/opam-cross-ios). Let me know if you are interested in some or all of these changes, and I can submit a PR.

### PR DESCRIPTION
**Pull request by dboris**
Closes #15

### CODE REVIEW

**Review by whitequark — APPROVED** [review]
LGTM

**Comment by whitequark** [comment]
Would you like to become an opam-cross-ios maintainer?

**Comment by dboris** [comment]
Yes, I would be happy to.

**Comment by whitequark** [comment]
Invited.

**Pull request merged**
